spin_version = "1"
name = "prolog-php"
description = "Prolog Home Page"
trigger = { type = "http", base = "/" }
version = "0.0.0"

[[component]]
id = "prolog"
description = "PHP: Prolog Home Page"
source = "wasm/tpl.wasm"
files = [{ source = "cgi-bin/", destination = "/"}, { source = "lib/", destination = "/lib"}, { source = "public_html/", destination = "/public_html"}]
[component.trigger]
route = "/..."
[component.trigger.executor]
type = "wagi"
# TODO: fix --library
argv = "tpl --library /lib -q -f /lib/cgi -f /lib/php -g handle(\"${SCRIPT_NAME}\") -- ${ARGS}"
