spin_version = "1"
name = "prolog-php"
description = "Prolog Home Page"
trigger = { type = "http", base = "/" }
version = "0.2.0"

[[component]]
id = "prolog"
description = "PHP: Prolog Home Page"
files = [{ source = "www/", destination = "/"}]
allowed_http_hosts = ["insecure:allow-all"]
key_value_stores = ["default"]
#source = "libtpl-spin.wasm"
[component.source]
url = "https://github.com/guregu/trealla/releases/download/v0.17.2/libtpl-spin.wasm"
digest = "sha256:c9fae6c5cfebda16b9c43de904c51d008c0c098b9a88be578230a9873482ef08"
[component.trigger]
route = "/..."
[component.environment]
#INIT = "init-custom.pl"
TPL_LIBRARY_PATH = "library"
PHP_ROOT = "public_html"
#POSTGRES_URL = "postgres://root:password@example.com/neondb"

[[component]]
id = "assets"
description = "static files"
files = [{ source = "www/assets/", destination = "/"}]
[component.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm"
digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b"
[component.trigger]
route = "/assets/..."
