spin_manifest_version = 2

[application]
name = "prolog-php"
version = "0.5.0"
description = "Prolog Home Page"
[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-prolog"
component = "prolog"
route = "/..."
[[trigger.http]]
id = "trigger-assets"
component = "assets"
route = "/assets/..."

[component.prolog]
description = "PHP: Prolog Home Page"
files = [{ source = "www/", destination = "/" }]
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*", "http://*:*", "https://*:*", "http://self"]
key_value_stores = ["default"]
sqlite_databases = ["default"]
# for local testing:
#source = "libtpl-spin.wasm"
# official release
[component.prolog.source]
url = "https://github.com/guregu/trealla/releases/download/v0.26.7/libtpl-spin.wasm"
digest = "sha256:41f9006515508b76820471b28954aa2c597dc5a88729b5a9c5694b7186e5b7fb"
[component.prolog.build]
command = "true"
watch = ["www/**/*"]
[component.prolog.environment]
TPL_LIBRARY_PATH = "library"
PHP_ROOT = "public_html"
# used by the guestbook example:
# (feel free to delete)
BANNED_WORDS = "fhqwhgads,skub"

[component.assets]
description = "static files"
files = [{ source = "www/assets/", destination = "/" }]
[component.assets.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm"
digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148"
