spin_version = "1"
name = "prolog-php"
description = "Prolog Home Page"
trigger = { type = "http", base = "/" }
version = "0.0.0"

[[component]]
id = "prolog"
description = "PHP: Prolog Home Page"
source = "wasm/tpl.wasm"
files = [{ source = "cgi-bin/", destination = "/"}, { source = "std/", destination = "/std"}]
[component.trigger]
route = "/..."
[component.trigger.executor]
type = "wagi"
# argv = "tpl -f /std/cgi -f /std/php -f ${SCRIPT_NAME} -g main -- ${ARGS}"
argv = "tpl -f /std/cgi -f /std/php -g handle(\"${SCRIPT_NAME}\") -- ${ARGS}"
