spin_version = "1"
name = "prolog-php"
description = "Prolog Home Page"
trigger = { type = "http", base = "/" }
version = "0.3.0"

[[component]]
id = "prolog"
description = "PHP: Prolog Home Page"
source = "wapm_packages/guregu/trealla@0.11.27/tpl.wasm"
files = [{ source = "www/", destination = "/"}]
[component.trigger]
route = "/..."
[component.build]
command = "wapm install"
[component.trigger.executor]
type = "wagi"
argv = "tpl --library /lib -q -f /lib/cgi -f /lib/php --ns -g call_cleanup(handle(\"${SCRIPT_NAME}\"),halt) -- ${ARGS}"
